# Generated by Django 4.2.1 on 2023-06-26 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='authormodel',
            table='author_pro',
        ),
        migrations.AlterModelTable(
            name='bookcategorymodel',
            table='book_category_pro',
        ),
        migrations.AlterModelTable(
            name='bookmodel',
            table='book_pro',
        ),
    ]
